### ISSUE TITLE
Cannot reach service from Kubernetes Ingress Controller when mTLS is implemented in service mesh

### ISSUE THREAD

**Issue by mpaulgreen** [mpaulgreen/kong-demo#9]
When mTLS is implemented for default mesh. We cannot reach the service from KIC.  Following is the trafficpermission configured

```
apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  name: ingress-to-mesh
spec:
  destinations:
  - match:
      kuma.io/service: '*'
  sources:
  - match:
      kuma.io/service: kong-kong-proxy_kong_svc_8000
```
